package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/albe2669/spotify-viewer/generated"
)

// PlayerState is the resolver for the playerState field.
func (r *subscriptionResolver) PlayerState(ctx context.Context) (<-chan *generated.PlayerState, error) {
	clientID, ch := r.PlayerStateHandler.AddClient(ctx)
	fmt.Println("clientID:", clientID)
	return ch, nil
}
